//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


int fisrtNumber = 1;
int secondNumber = 2;
int sum =0 ;
while(fisrtNumber < 4000000){
    (fisrtNumber%2 == 0)? sum += fisrtNumber: "";
    (secondNumber%2 == 0)? sum += secondNumber:"";
    
    fisrtNumber = fisrtNumber + secondNumber
    secondNumber = fisrtNumber + secondNumber
    
}
print sum
